name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: erlang:22.1.8
    steps:
    - uses: actions/checkout@v1
    - name: Compile
      run: rebar3 compile
    - name: Check formatting
      run: rebar3 steamroll --check
    - name: Run tests
      run: rebar3 test
    - name: Run dialyzer
      run: rebar3 dialyzer
