name: build_matrix

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        otp: [21, 22, 23]
    runs-on: ubuntu-latest
    container:
      image: erlang:${{ matrix.otp }}
    steps:
    - uses: actions/checkout@v1
    - name: Compile
      run: rebar3 compile
    - name: Check formatting
      run: rebar3 steamroll --check
    - name: Run tests
      run: rebar3 test
    - name: Run dialyzer
      run: rebar3 dialyzer
